# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Audit Node.js dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3.0.0
      with:
        cache: 'npm'
    - run: npm ci
    - name: Run audit
      uses: oke-py/npm-audit-action@v1.8.4
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_labels: javascript,dependencies,possible-vulnerability
        dedupe_issues: true

